addons:
  sonarqube: true
env:
  global:
  - secure: nPh4tS+SEWHXmm4keHBLQSVMdwMyUJRFNDFhYt+DezK4ruU8D0ZFhssY3I7anhX/FZ4pG64uVjXWcaIIqZMzJvs4000Z3Ym+7sC/3HSV27qdjQCvJPp6tjfkWtSPomqaW8MPmrG69KZNlANYrbAkMcPTR7zxCYwwnMfQurRmFi80d/2O5xCw5NxXBeJ/6nPmiUtpN8njdI4yhSjrBtYuGtwjm0zh1ZAo6l/1928+qXKooXXDHM1d1qpMgIB3sQW6ggSrpJy2W0tfEaUHbMB+MIoOuu3QdVvpicw61Vb23jGNrnsSvBDFi0ydYlmGaKzz9Fss1jMGQEon1ik/rA83VLZ7HusfF7JjDv+2ZArIGyL6BoDRUkadpPP3KIeWgVRA634GZAkqxz4zarEHjTMTK7mgolw6H9vnTabfcCabhmHVmaf+ZCHhXQZHku7ScxRMl6oPLyZSCluuvq9ISq7B/iHSuIdXgzUZreflYip6uYiTqmLtDvtIN0L7yj1elZtmE1suSDCkSOLIw92h0u27mW2JFNRKzjdaafSYjyLB/4IAoGSbLPKeWY0Dqg1eQSGQWLkRKxGhx5AtdtOUvX0VesyGor8g4UvFCmPvriONhPBShWBHP18CLwigFfKSDlIcUH2idhs/O1Uxsyti20tXv1hjhWntinv+9ekHj5/S6Dw=
  - secure: hrJ/DkPVNsiDTTn3W/pCQ+z121tITxQfomjQ+xRqB4C4ynJc/Du0kWuyloas86aqT/bNh3ht3cw7DPZQn6um7ALHsfUQXiEtjqc0TAMm9jxzRq1eC+c/CsEDBZd92ygwMoMWgWsquvhWdnzxM9kIRAACErz/hiA0k4FI7BIYD5gt/19E+dAWas0+Qx2H5VHcQLSoeRdhzozK+vbu7n8nuDTs8+BYeBSNOhqLG8nEV5xS0uukP9s8JWojYusXIrC+eD6PsGxwnTJltAFmDBBwavGcb450EaCurHCT2WA0WmfjU24zdD4ZVLQmBpNShyXA2ujJXpXthXSdhy7kksNI4u37Se2CfUVN1sRFNvQncN9brroY0KYKMDWPsaNPRef9WqG+J3UG3z0xpI8rw93wwO3QNLCKeW52fi/eSsA1tF6T3rlzYxBfEnAv9amUlvGZd5CpKR/jd5DNxMRG7hS/4nekYi8Z4YyKqAz7yQraY2Hi06ReaFWZT2gANL+cfS6hsEkMWQXH1EFMclV0zje5+TJHw7gcXj2n9N2/EGKXrs06MLtf/+SYIUHpoPuKMo1osa2kTOCnHbhUZh4S4E1lK3oGriibd/87JPoVtSJg7y4pgCO9n8BsMhVf1IDqybrsnGR1Q6JL8jxVUWbDMvEqsrj4KMRGykTJN557WyoFWEs=
  - GRADLE_OPTS=-Dorg.gradle.daemon=false 
language: java
script:
- jdk_switcher use oraclejdk7
- ./gradlew clean
- ./gradlew build
- ./gradlew test
- ./gradlew integrationTest
- jdk_switcher use oraclejdk8
- ./gradlew clean
- ./gradlew build
- ./gradlew test
- ./gradlew integrationTest
- ./gradlew pitest
- sonar-scanner -Dsonar.login=$SONAR_HCL
after_success:
- .travis/publish-javadoc.sh
- .travis/publish-junitreport.sh
- .travis/publish-pitest.sh
- .travis/publish-owaspdependency.sh
